### ISSUE TITLE
USB printing support

### ISSUE THREAD

**Issue by mholl1983** [russinnes/ASUS-RT-N600-OpenWRT#1]
Hi, does this build of openwrt allow for the USB port to work, ex as a printer server?

**Comment by russinnes** [comment]
Yes, but your best option at this point is to use the image for the Asus 1200AC (v1) image. It's in this repo as well, or you can get it from openwrt.

**Comment by mholl1983** [comment]
Cool, thx. Will it work to flash within the current OpenWRT image (via Luci) or do I need to start over w/ the recovery tool?

**Comment by russinnes** [comment]
You can flash from Luci. You may need to manually override as it may see a different model number. The option to do so will present itself.
