### ISSUE TITLE
Can't make rt-n19 (n600) to work

### ISSUE THREAD

**Issue by Treeger** [russinnes/ASUS-RT-N600-OpenWRT#2]
Hey, @russinnes!
I tried your firmwares with `Asus recovery firmware` for my rt-n19 (n600) router, but it did not work. 
I followed the instruction but after the final step, DHCP never came up and I can't access the router.
Can you help and point me in the direction?

**Comment by russinnes** [comment]
What are your LEDs doing?On Feb 13, 2023, at 1:35 AM, Konstantin Rebrov ***@***.***> wrote:﻿
Hey, @russinnes!
I tried your firmwares with Asus recovery firmware for my rt-n19 (n600) router, but it did not work.
I followed the instruction but after the final step, DHCP never came up.
Can you help and point me in the direction?

**Comment by Treeger** [comment]
The lights are not up, I got only the power one.
I also tried the official firmware and it does work.

**Comment by russinnes** [comment]
Are you using the asus firmware recovery tool or tftp?On Feb 14, 2023, at 12:41 PM, Konstantin Rebrov ***@***.***> wrote:﻿
The lights are not up, I got only the power one.
I also tried the official firmware and it does work.

**Comment by russinnes** [comment]
Sorry, you are using an RT-N19 which is not an RT-N600. Completely different board. Your device may well be N600 for speed, but not an N600 model. On Feb 14, 2023, at 12:41 PM, Konstantin Rebrov ***@***.***> wrote:﻿
The lights are not up, I got only the power one.
I also tried the official firmware and it does work.
